"use strict";
document.addEventListener("DOMContentLoaded",()=>{
 const form=document.getElementById("registrationForm"),childrenContainer=document.getElementById("childrenContainer"),childTemplate=document.getElementById("childTemplate"),addChildButton=document.getElementById("addChildButton"),formMessage=document.getElementById("formMessage"),submitButton=document.getElementById("submitButton"),submitButtonText=document.getElementById("submitButtonText"),submitSpinner=document.getElementById("submitSpinner"),closedState=document.getElementById("closedState");
 const cfg=window.APP_CONFIG||{}; let isSubmitting=false,availability={open:false,reason:"setup",registered:0,remaining:cfg.maxParticipants||12};
 addChild(); addChildButton.addEventListener("click",addChild); form.addEventListener("input",e=>clearInvalidState(e.target)); form.addEventListener("change",e=>clearInvalidState(e.target)); form.addEventListener("submit",handleSubmit); checkAvailability();
 function validEndpoint(){return typeof cfg.appsScriptUrl==="string"&&cfg.appsScriptUrl.startsWith("https://script.google.com/macros/s/")&&cfg.appsScriptUrl.endsWith("/exec")}
 async function checkAvailability(){
   const deadline=new Date(cfg.registrationDeadline); if(Date.now()>deadline.getTime()){setAvailability({open:false,reason:"deadline",registered:0,remaining:0});return}
   if(!validEndpoint()){setAvailability({open:false,reason:"setup",registered:0,remaining:cfg.maxParticipants||12});return}
   try{const url=`${cfg.appsScriptUrl}?action=status&_=${Date.now()}`;const res=await fetch(url,{method:"GET",redirect:"follow",cache:"no-store"});if(!res.ok)throw new Error(`Status ${res.status}`);setAvailability(await res.json())}catch(err){console.error(err);setAvailability({open:false,reason:"unavailable",registered:0,remaining:0})}
 }
 function setAvailability(data){availability=data;const max=Number(data.maxParticipants||cfg.maxParticipants||12),registered=Number(data.registered||0),remaining=Math.max(0,Number(data.remaining??max-registered));document.getElementById("capacityCount").textContent=`${registered} / ${max}`;document.getElementById("capacityBar").style.width=`${Math.min(100,(registered/max)*100)}%`;const title=document.getElementById("statusTitle"),text=document.getElementById("statusText");
   if(data.open){title.textContent=`${remaining} participant spot${remaining===1?"":"s"} remaining`;text.textContent="Registration is open until August 4, 2026 at 11:59 PM CT, unless capacity is reached first.";form.classList.remove("hidden");closedState.classList.add("hidden");submitButton.disabled=false;return}
   form.classList.add("hidden");closedState.classList.remove("hidden");const closedTitle=document.getElementById("closedTitle"),closedMessage=document.getElementById("closedMessage");
   if(data.reason==="full"){title.textContent="Registration full";text.textContent="All 12 participant spots have been filled.";closedTitle.textContent="Registration is full";closedMessage.textContent="We have reached the maximum capacity of 12 participants. Thank you for the incredible interest in the EGP research study."}
   else if(data.reason==="deadline"){title.textContent="Registration closed";text.textContent="The registration deadline has passed.";closedTitle.textContent="Registration has closed";closedMessage.textContent="Registration closed on August 4, 2026 at 11:59 PM CT. Thank you for your interest in Euler’s Golden Pie."}
   else if(data.reason==="setup"){title.textContent="Portal setup required";text.textContent="Connect the new Google Apps Script deployment to activate registration.";closedTitle.textContent="Almost ready";closedMessage.textContent="The new registration backend has not been connected yet. Add the deployment URL in config.js to open the portal."}
   else{title.textContent="Availability check unavailable";text.textContent="Please try again shortly.";closedTitle.textContent="Registration temporarily unavailable";closedMessage.textContent="We could not confirm the remaining capacity. Please refresh the page in a few minutes."}
 }
 function addChild(){const fragment=childTemplate.content.cloneNode(true),card=fragment.querySelector(".child-card");card.dataset.childKey=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;childrenContainer.appendChild(fragment);renumberChildren();updateRemoveButtons();}
 function removeChild(card){if(childrenContainer.querySelectorAll(".child-card").length<=1)return;card.remove();renumberChildren();updateRemoveButtons()}
 function renumberChildren(){childrenContainer.querySelectorAll(".child-card").forEach((card,index)=>{const n=index+1;card.querySelector(".child-title").textContent=`Child ${n}`;card.querySelectorAll("[data-child-field]").forEach(field=>{field.id=`child-${n}-${field.dataset.childField}`;const label=field.closest(".field-group")?.querySelector("label");if(label)label.htmlFor=field.id});const remove=card.querySelector(".remove-child-button");remove.onclick=()=>removeChild(card);remove.setAttribute("aria-label",`Remove Child ${n}`)})}
 function updateRemoveButtons(){const cards=childrenContainer.querySelectorAll(".child-card");cards.forEach(card=>card.querySelector(".remove-child-button").hidden=cards.length===1)}
 async function handleSubmit(e){e.preventDefault();if(isSubmitting||!availability.open)return;clearMessage();clearAllInvalidStates();if(!validateForm()){showMessage("Please complete all required fields and consent statements.","error");scrollToFirstInvalid();return}const childCount=childrenContainer.querySelectorAll(".child-card").length;if(childCount>availability.remaining){showMessage(`Only ${availability.remaining} participant spot${availability.remaining===1?" is":"s are"} currently available. Please remove a participant or refresh the page.`,"error");return}
   setSubmitting(true);try{const body=new URLSearchParams({payload:JSON.stringify(collectRegistrationData())});const res=await fetch(cfg.appsScriptUrl,{method:"POST",body,redirect:"follow"});const result=await res.json();if(!result.ok){setAvailability(result.status||{open:false,reason:result.code==="FULL"?"full":"unavailable"});throw new Error(result.message||"Registration was not accepted.")}localStorage.removeItem("egpFamilySubmissionToken");window.location.assign("pages/success.html")}catch(err){console.error(err);showMessage(err.message||"The registration could not be submitted. Please try again.","error");setSubmitting(false);checkAvailability()}}
 function validateForm(){let valid=true;form.querySelectorAll("input[required],select[required],textarea[required]").forEach(field=>{if(!validateField(field))valid=false});return valid}
 function validateField(field){let valid=field.type==="checkbox"?field.checked:(field.checkValidity()&&String(field.value).trim()!=="");if(field.dataset.childField==="age"&&field.value){const age=Number(field.value);valid=Number.isInteger(age)&&age>=5&&age<=17}if(field.type==="email"&&field.value)valid=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.value.trim());if(!valid)setInvalidState(field);return valid}
 function setInvalidState(field){field.classList.add("invalid");field.setAttribute("aria-invalid","true");if(field.type==="checkbox")field.closest(".checkbox-card")?.classList.add("invalid")}
 function clearInvalidState(field){if(!(field instanceof HTMLElement))return;field.classList.remove("invalid");field.removeAttribute("aria-invalid");if(field.type==="checkbox")field.closest(".checkbox-card")?.classList.remove("invalid")}
 function clearAllInvalidStates(){form.querySelectorAll(".invalid").forEach(el=>{el.classList.remove("invalid");el.removeAttribute("aria-invalid")})}
 function scrollToFirstInvalid(){const x=form.querySelector(".invalid");x?.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>x?.focus?.({preventScroll:true}),350)}
 function collectRegistrationData(){return{submissionToken:getToken(),parent:{firstName:val("parentFirstName"),lastName:val("parentLastName"),email:val("parentEmail").toLowerCase(),phone:val("parentPhone"),relationship:val("parentRelationship"),city:val("city")},children:[...childrenContainer.querySelectorAll(".child-card")].map(card=>{const get=n=>String(card.querySelector(`[data-child-field="${n}"]`)?.value||"").trim();return{firstName:get("firstName"),lastName:get("lastName"),age:get("age"),gradeLevel:get("gradeLevel"),schoolName:get("schoolName"),accommodations:get("accommodations")}}),consent:{pisRead:checked("pisRead"),guardianAuthority:checked("guardianAuthority"),understandsActivities:checked("understandsActivities"),voluntaryParticipation:checked("voluntaryParticipation"),parentPermission:checked("parentPermission"),studentAssentAcknowledgment:checked("studentAssentAcknowledgment"),dataUsePermission:checked("dataUsePermission"),whatsappPermission:checked("whatsappPermission"),photoPermission:checked("photoPermission"),videoPermission:checked("videoPermission"),accuracyConfirmation:checked("accuracyConfirmation")},website:val("website"),submittedAt:new Date().toISOString(),sourcePage:location.href}}
 function val(id){return String(document.getElementById(id)?.value||"").trim()} function checked(id){return !!document.getElementById(id)?.checked}
 function getToken(){let t=localStorage.getItem("egpFamilySubmissionToken");if(!t){t=crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;localStorage.setItem("egpFamilySubmissionToken",t)}return t}
 function setSubmitting(on){isSubmitting=on;submitButton.disabled=on;submitButtonText.textContent=on?"Securing participant spot…":"Submit registration";submitSpinner.classList.toggle("hidden",!on)}
 function showMessage(message,type){formMessage.textContent=message;formMessage.className=`message message-${type}`;formMessage.scrollIntoView({behavior:"smooth",block:"center"})}function clearMessage(){formMessage.textContent="";formMessage.className="message hidden"}
});
